swagger: '2.0'
info:
  version: '1.0'
  title: BUMA DSM
  contact: {}
host: buma.predictdsm.com
basePath: /api/v2/driverbehaviour
securityDefinitions: {}
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /encode:
    post:
      summary: Encode
      tags:
        - V2
      operationId: Encode
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: false
          enum:
            - application/json
          type: string
          description: ''
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/EncodeRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
          examples:
            application/json:
              success: true
              error: null
              message: Data retrieved.
              data: ZGVtby1zdWFkbWluOlByZWRpY3REU00zMjEr
          headers:
            Date:
              type: string
              default: Sun, 06 Mar 2022 16:45:09 GMT
            Server:
              type: string
              default: Apache/2.4.51 (Win64) OpenSSL/1.1.1d PHP/7.4.3
            X-Powered-By:
              type: string
              default: PHP/7.4.3
            Cache-Control:
              type: string
              default: no-cache, private
            X-RateLimit-Limit:
              type: string
              default: '60'
            X-RateLimit-Remaining:
              type: string
              default: '59'
            Content-Length:
              type: string
              default: '103'
            Keep-Alive:
              type: string
              default: timeout=5, max=100
            Connection:
              type: string
              default: Keep-Alive
  /alarm-types:
    post:
      summary: Alarm Types
      tags:
        - V2
      operationId: AlarmTypes
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: false
          enum:
            - application/json
          type: string
          description: ''
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/AlarmTypesRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response1'
          examples:
            application/json:
              success: true
              error: null
              message: Driver retrieved.
              data:
                - Camera-covering alarm
                - Driver Distraction
                - Driver Fatigue
                - Forward Collision Warning
                - High-speed alarm
                - IO 1
                - No driver
                - Phone Detection
                - Smoking Detection
                - Video loss alarm
                - Yawning Detection
              total_data: 11
          headers:
            Date:
              type: string
              default: Sun, 06 Mar 2022 16:57:09 GMT
            Server:
              type: string
              default: Apache/2.4.51 (Win64) OpenSSL/1.1.1d PHP/7.4.3
            X-Powered-By:
              type: string
              default: PHP/7.4.3
            Cache-Control:
              type: string
              default: no-cache, private
            X-RateLimit-Limit:
              type: string
              default: '60'
            X-RateLimit-Remaining:
              type: string
              default: '60'
            Content-Length:
              type: string
              default: '289'
            Keep-Alive:
              type: string
              default: timeout=5, max=100
            Connection:
              type: string
              default: Keep-Alive
  /sites:
    post:
      summary: Sites
      tags:
        - V2
      operationId: Sites
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: false
          enum:
            - application/json
          type: string
          description: ''
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/SitesRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response2'
          examples:
            application/json:
              success: true
              error: null
              message: Data retrieved.
              data:
                - SiteId: BMOBUS
                  Name: BMO - BUS
                - SiteId: BMOFUELTRUCK
                  Name: BMO - FUEL TRUCK
                - SiteId: BMOHAULCOAL
                  Name: BMO - HAULING COAL
                - SiteId: BMOHAULCOALSUARAN
                  Name: BMO - HAULING COAL SUARAN
                - SiteId: BMOMAINHAUL
                  Name: BMO - OB HAULLER
              total_data: 5
          headers:
            Date:
              type: string
              default: Sun, 06 Mar 2022 16:59:34 GMT
            Server:
              type: string
              default: Apache/2.4.51 (Win64) OpenSSL/1.1.1d PHP/7.4.3
            X-Powered-By:
              type: string
              default: PHP/7.4.3
            Cache-Control:
              type: string
              default: no-cache, private
            X-RateLimit-Limit:
              type: string
              default: '60'
            X-RateLimit-Remaining:
              type: string
              default: '58'
            Content-Length:
              type: string
              default: '342'
            Keep-Alive:
              type: string
              default: timeout=5, max=100
            Connection:
              type: string
              default: Keep-Alive
  /operators:
    post:
      summary: Operators
      tags:
        - V2
      operationId: Operators
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: false
          enum:
            - application/json
          type: string
          description: ''
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/OperatorsRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response3'
          examples:
            application/json:
              success: true
              error: null
              message: Data retrieved.
              data:
                - Name: Semol Nico Titawano
                  OperatorId: 4
                  NIK: '10026867'
                - Name: Yosua Sambuaga Tumurang
                  OperatorId: 5
                  NIK: '10026868'
                - Name: Adi Pongsamma
                  OperatorId: 6
                  NIK: '10026509'
                - Name: Jalif
                  OperatorId: 7
                  NIK: '10026510'
                - Name: Moh. Aswan
                  OperatorId: 8
                  NIK: '10026511'
              total_data: 5
          headers:
            Date:
              type: string
              default: Sun, 06 Mar 2022 17:00:17 GMT
            Server:
              type: string
              default: Apache/2.4.51 (Win64) OpenSSL/1.1.1d PHP/7.4.3
            X-Powered-By:
              type: string
              default: PHP/7.4.3
            Cache-Control:
              type: string
              default: no-cache, private
            X-RateLimit-Limit:
              type: string
              default: '60'
            X-RateLimit-Remaining:
              type: string
              default: '59'
            Content-Length:
              type: string
              default: '371'
            Keep-Alive:
              type: string
              default: timeout=5, max=100
            Connection:
              type: string
              default: Keep-Alive
  /equipments:
    post:
      summary: Equipments
      tags:
        - V2
      operationId: Equipments
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: false
          enum:
            - application/json
          type: string
          description: ''
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/EquipmentsRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response4'
          examples:
            application/json:
              success: true
              error: null
              message: Data retrieved.
              data:
                - EquipmentId: '0099025195'
                  EquipmentNo: BM 522
                  EquipmentName: BMO - BM 522 - BUS
                  Camera:
                    - CameraId: 0099025195-01
                      CameraName: ADAS Camera
                      CameraStatus: Active
                    - CameraId: 0099025195-02
                      CameraName: DSM Camera
                      CameraStatus: Active
                    - CameraId: 0099025195-03
                      CameraName: Cabin Camera
                      CameraStatus: Active
                - EquipmentId: 00990253CC
                  EquipmentNo: BM 572
                  EquipmentName: BMO - BM 572 - BUS
                  Camera:
                    - CameraId: 00990253CC-01
                      CameraName: ADAS Camera
                      CameraStatus: Active
                    - CameraId: 00990253CC-02
                      CameraName: DSM Camera
                      CameraStatus: Active
                    - CameraId: 00990253CC-03
                      CameraName: Cabin Camera
                      CameraStatus: Active
              total_data: 2
          headers:
            Date:
              type: string
              default: Sun, 06 Mar 2022 17:03:56 GMT
            Server:
              type: string
              default: Apache/2.4.51 (Win64) OpenSSL/1.1.1d PHP/7.4.3
            X-Powered-By:
              type: string
              default: PHP/7.4.3
            Cache-Control:
              type: string
              default: no-cache, private
            X-RateLimit-Limit:
              type: string
              default: '60'
            X-RateLimit-Remaining:
              type: string
              default: '57'
            Content-Length:
              type: string
              default: '761'
            Keep-Alive:
              type: string
              default: timeout=5, max=99
            Connection:
              type: string
              default: Keep-Alive
  /deviations:
    post:
      summary: Deviations
      tags:
        - V2
      operationId: Deviations
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: Accept
          in: header
          required: true
          type: string
          description: ''
        - name: Content-Type
          in: header
          required: false
          enum:
            - application/json
          type: string
          description: ''
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/DeviationsRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Deviations'
          examples:
            application/json:
              success: true
              error: null
              message: Data retrieved.
              data:
                - Longitude: '116.569951'
                  Latitude: '0.292716'
                  TicketNumber: IPR - PMVV16143-PDSM00000425
                  DeviationId: 287042
                  OperatorId: null
                  OperatorName: ''
                  EquipmentId: 00990268AE
                  EquipmentName: IPR - PMVV16143
                  EquipmentSpeed: 48
                  unSafeAct: Driver Fatigue
                  unSafeActUtcDate: '2022-01-01 14:45:04'
                  ReportTime: '2022-01-01 15:14:51'
                  Shift: 2
                  Duration: 7
                  Direction: East
                  Angle: 110
                  SiteName: IPR - HAULING COAL
                  ValidationStatus: Validated
                  FollowupStatus: Close
                  DeviationEvidences:
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDdfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDhfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDFfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
                - Longitude: '116.278100'
                  Latitude: '0.472105'
                  TicketNumber: IPR - PMVV16117-PDSM00000309
                  DeviationId: 286926
                  OperatorId: null
                  OperatorName: ''
                  EquipmentId: 009902517A
                  EquipmentName: IPR - PMVV16117
                  EquipmentSpeed: 52
                  unSafeAct: Driver Fatigue
                  unSafeActUtcDate: '2022-01-01 12:39:24'
                  ReportTime: '2022-01-01 13:10:46'
                  Shift: 2
                  Duration: 7
                  Direction: East
                  Angle: 102
                  SiteName: IPR - HAULING COAL
                  ValidationStatus: Validated
                  FollowupStatus: Close
                  DeviationEvidences:
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzQxL0NIQU5ORUxfMDdfMjAyMjAxMDEyMDM5MjFfMjAyMjAxMDEyMDM5MjcubXA0
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzQxL0NIQU5ORUxfMDhfMjAyMjAxMDEyMDM5MjFfMjAyMjAxMDEyMDM5MjcubXA0
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzQxL0NIQU5ORUxfMDFfMjAyMjAxMDEyMDM5MjFfMjAyMjAxMDEyMDM5MjcubXA0
                - Longitude: '116.275741'
                  Latitude: '0.472320'
                  TicketNumber: IPR - PMVV16117-PDSM00000324
                  DeviationId: 286941
                  OperatorId: null
                  OperatorName: ''
                  EquipmentId: 009902517A
                  EquipmentName: IPR - PMVV16117
                  EquipmentSpeed: 43
                  unSafeAct: Driver Fatigue
                  unSafeActUtcDate: '2022-01-01 12:39:05'
                  ReportTime: '2022-01-01 13:26:35'
                  Shift: 2
                  Duration: 7
                  Direction: East
                  Angle: 90
                  SiteName: IPR - HAULING COAL
                  ValidationStatus: Validated
                  FollowupStatus: Close
                  DeviationEvidences:
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzU4L0NIQU5ORUxfMDdfMjAyMjAxMDEyMDM5MDJfMjAyMjAxMDEyMDM5MDgubXA0
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzU4L0NIQU5ORUxfMDhfMjAyMjAxMDEyMDM5MDJfMjAyMjAxMDEyMDM5MDgubXA0
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzU4L0NIQU5ORUxfMDFfMjAyMjAxMDEyMDM5MDJfMjAyMjAxMDEyMDM5MDgubXA0
                - Longitude: '116.275331'
                  Latitude: '0.472320'
                  TicketNumber: IPR - PMVV16117-PDSM00000371
                  DeviationId: 286988
                  OperatorId: null
                  OperatorName: ''
                  EquipmentId: 009902517A
                  EquipmentName: IPR - PMVV16117
                  EquipmentSpeed: 39
                  unSafeAct: Driver Fatigue
                  unSafeActUtcDate: '2022-01-01 12:39:01'
                  ReportTime: '2022-01-01 14:10:09'
                  Shift: 2
                  Duration: 7
                  Direction: East
                  Angle: 90
                  SiteName: IPR - HAULING COAL
                  ValidationStatus: Validated
                  FollowupStatus: Close
                  DeviationEvidences:
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2Nzk1L0NIQU5ORUxfMDdfMjAyMjAxMDEyMDM4NThfMjAyMjAxMDEyMDM5MDQubXA0
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2Nzk1L0NIQU5ORUxfMDhfMjAyMjAxMDEyMDM4NThfMjAyMjAxMDEyMDM5MDQubXA0
                    - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2Nzk1L0NIQU5ORUxfMDFfMjAyMjAxMDEyMDM4NThfMjAyMjAxMDEyMDM5MDQubXA0
              total_data: 4
          headers:
            Date:
              type: string
              default: Sun, 06 Mar 2022 17:06:43 GMT
            Server:
              type: string
              default: Apache/2.4.51 (Win64) OpenSSL/1.1.1d PHP/7.4.3
            X-Powered-By:
              type: string
              default: PHP/7.4.3
            Cache-Control:
              type: string
              default: no-cache, private
            X-RateLimit-Limit:
              type: string
              default: '60'
            X-RateLimit-Remaining:
              type: string
              default: '59'
            Content-Length:
              type: string
              default: '4911'
            Keep-Alive:
              type: string
              default: timeout=5, max=100
            Connection:
              type: string
              default: Keep-Alive
definitions:
  EncodeRequest:
    title: EncodeRequest
    example:
      origin: https://digital-dev-apm-001.azure-api.net
      username: demo-suadmin
      password: PredictDSM321+
    type: object
    properties:
      origin:
        type: string
      username:
        type: string
      password:
        type: string
    required:
      - origin
      - username
      - password
  Response:
    title: Response
    example:
      success: true
      error: null
      message: Data retrieved.
      data: ZGVtby1zdWFkbWluOlByZWRpY3REU00zMjEr
    type: object
    properties:
      success:
        type: boolean
      error:
        type: string
      message:
        type: string
      data:
        type: string
    required:
      - success
      - error
      - message
      - data
  AlarmTypesRequest:
    title: AlarmTypesRequest
    example:
      origin: https://digital-dev-apm-001.azure-api.net
      api_token: ZGVtby1zdWFkbWluOlByZWRpY3REU00zMjEr
      search: ''
      size: 100
    type: object
    properties:
      origin:
        type: string
      api_token:
        type: string
      search:
        type: string
      size:
        type: integer
        format: int32
    required:
      - origin
      - api_token
      - search
      - size
  Response1:
    title: Response1
    example:
      success: true
      error: null
      message: Driver retrieved.
      data:
        - Camera-covering alarm
        - Driver Distraction
        - Driver Fatigue
        - Forward Collision Warning
        - High-speed alarm
        - IO 1
        - No driver
        - Phone Detection
        - Smoking Detection
        - Video loss alarm
        - Yawning Detection
      total_data: 11
    type: object
    properties:
      success:
        type: boolean
      error:
        type: string
      message:
        type: string
      data:
        type: array
        items:
          type: string
      total_data:
        type: integer
        format: int32
    required:
      - success
      - error
      - message
      - data
      - total_data
  SitesRequest:
    title: SitesRequest
    example:
      origin: https://digital-dev-apm-001.azure-api.net
      api_token: ZGVtby1zdWFkbWluOlByZWRpY3REU00zMjEr
      search: ''
      size: 5
    type: object
    properties:
      origin:
        type: string
      api_token:
        type: string
      search:
        type: string
      size:
        type: integer
        format: int32
    required:
      - origin
      - api_token
      - search
      - size
  Response2:
    title: Response2
    example:
      success: true
      error: null
      message: Data retrieved.
      data:
        - SiteId: BMOBUS
          Name: BMO - BUS
        - SiteId: BMOFUELTRUCK
          Name: BMO - FUEL TRUCK
        - SiteId: BMOHAULCOAL
          Name: BMO - HAULING COAL
        - SiteId: BMOHAULCOALSUARAN
          Name: BMO - HAULING COAL SUARAN
        - SiteId: BMOMAINHAUL
          Name: BMO - OB HAULLER
      total_data: 5
    type: object
    properties:
      success:
        type: boolean
      error:
        type: string
      message:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/Datum'
      total_data:
        type: integer
        format: int32
    required:
      - success
      - error
      - message
      - data
      - total_data
  Datum:
    title: Datum
    example:
      SiteId: BMOBUS
      Name: BMO - BUS
    type: object
    properties:
      SiteId:
        type: string
      Name:
        type: string
    required:
      - SiteId
      - Name
  OperatorsRequest:
    title: OperatorsRequest
    example:
      origin: https://digital-dev-apm-001.azure-api.net
      api_token: ZGVtby1zdWFkbWluOlByZWRpY3REU00zMjEr
      search: ''
      size: 5
    type: object
    properties:
      origin:
        type: string
      api_token:
        type: string
      search:
        type: string
      size:
        type: integer
        format: int32
    required:
      - origin
      - api_token
      - search
      - size
  Response3:
    title: Response3
    example:
      success: true
      error: null
      message: Data retrieved.
      data:
        - Name: Semol Nico Titawano
          OperatorId: 4
          NIK: '10026867'
        - Name: Yosua Sambuaga Tumurang
          OperatorId: 5
          NIK: '10026868'
        - Name: Adi Pongsamma
          OperatorId: 6
          NIK: '10026509'
        - Name: Jalif
          OperatorId: 7
          NIK: '10026510'
        - Name: Moh. Aswan
          OperatorId: 8
          NIK: '10026511'
      total_data: 5
    type: object
    properties:
      success:
        type: boolean
      error:
        type: string
      message:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/Datum1'
      total_data:
        type: integer
        format: int32
    required:
      - success
      - error
      - message
      - data
      - total_data
  Datum1:
    title: Datum1
    example:
      Name: Semol Nico Titawano
      OperatorId: 4
      NIK: '10026867'
    type: object
    properties:
      Name:
        type: string
      OperatorId:
        type: integer
        format: int32
      NIK:
        type: string
    required:
      - Name
      - OperatorId
      - NIK
  EquipmentsRequest:
    title: EquipmentsRequest
    example:
      origin: https://digital-dev-apm-001.azure-api.net
      api_token: ZGVtby1zdWFkbWluOlByZWRpY3REU00zMjEr
      search: ''
      siteId:
        - BMOBUS
      size: 100
    type: object
    properties:
      origin:
        type: string
      api_token:
        type: string
      search:
        type: string
      siteId:
        type: array
        items:
          type: string
      size:
        type: integer
        format: int32
    required:
      - origin
      - api_token
      - search
      - siteId
      - size
  Response4:
    title: Response4
    example:
      success: true
      error: null
      message: Data retrieved.
      data:
        - EquipmentId: '0099025195'
          EquipmentNo: BM 522
          EquipmentName: BMO - BM 522 - BUS
          Camera:
            - CameraId: 0099025195-01
              CameraName: ADAS Camera
              CameraStatus: Active
            - CameraId: 0099025195-02
              CameraName: DSM Camera
              CameraStatus: Active
            - CameraId: 0099025195-03
              CameraName: Cabin Camera
              CameraStatus: Active
        - EquipmentId: 00990253CC
          EquipmentNo: BM 572
          EquipmentName: BMO - BM 572 - BUS
          Camera:
            - CameraId: 00990253CC-01
              CameraName: ADAS Camera
              CameraStatus: Active
            - CameraId: 00990253CC-02
              CameraName: DSM Camera
              CameraStatus: Active
            - CameraId: 00990253CC-03
              CameraName: Cabin Camera
              CameraStatus: Active
      total_data: 2
    type: object
    properties:
      success:
        type: boolean
      error:
        type: string
      message:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/Datum2'
      total_data:
        type: integer
        format: int32
    required:
      - success
      - error
      - message
      - data
      - total_data
  Datum2:
    title: Datum2
    example:
      EquipmentId: '0099025195'
      EquipmentNo: BM 522
      EquipmentName: BMO - BM 522 - BUS
      Camera:
        - CameraId: 0099025195-01
          CameraName: ADAS Camera
          CameraStatus: Active
        - CameraId: 0099025195-02
          CameraName: DSM Camera
          CameraStatus: Active
        - CameraId: 0099025195-03
          CameraName: Cabin Camera
          CameraStatus: Active
    type: object
    properties:
      EquipmentId:
        type: string
      EquipmentNo:
        type: string
      EquipmentName:
        type: string
      Camera:
        type: array
        items:
          $ref: '#/definitions/Camera'
    required:
      - EquipmentId
      - EquipmentNo
      - EquipmentName
      - Camera
  Camera:
    title: Camera
    example:
      CameraId: 0099025195-01
      CameraName: ADAS Camera
      CameraStatus: Active
    type: object
    properties:
      CameraId:
        type: string
      CameraName:
        type: string
      CameraStatus:
        type: string
    required:
      - CameraId
      - CameraName
      - CameraStatus
  DeviationsRequest:
    title: DeviationsRequest
    example:
      origin: https://digital-dev-apm-001.azure-api.net
      api_token: ZGVtby1zdWFkbWluOlByZWRpY3REU00zMjEr
      search: ''
      StartTime: '2022-01-01 00:00:00'
      EndTime: '2022-01-01 23:59:59'
      SiteId: []
      EquipmentId: []
      AlarmTypes:
        - Driver Fatigue
      ValidationStatus:
        - Pending
        - Validated
      FollowupStatus:
        - Open
        - Close
      OperatorId: []
      size: 20
    type: object
    properties:
      origin:
        type: string
      api_token:
        type: string
      search:
        type: string
      StartTime:
        type: string
      EndTime:
        type: string
      SiteId:
        type: array
        items:
          type: string
      EquipmentId:
        type: array
        items:
          type: string
      AlarmTypes:
        type: array
        items:
          type: string
      ValidationStatus:
        type: array
        items:
          type: string
      FollowupStatus:
        type: array
        items:
          type: string
      OperatorId:
        type: array
        items:
          type: string
      size:
        type: integer
        format: int32
    required:
      - origin
      - api_token
      - search
      - StartTime
      - EndTime
      - SiteId
      - EquipmentId
      - AlarmTypes
      - ValidationStatus
      - FollowupStatus
      - OperatorId
      - size
  Deviations:
    title: Deviations
    example:
      success: true
      error: null
      message: Data retrieved.
      data:
        - Longitude: '116.569951'
          Latitude: '0.292716'
          TicketNumber: IPR - PMVV16143-PDSM00000425
          DeviationId: 287042
          OperatorId: null
          OperatorName: ''
          EquipmentId: 00990268AE
          EquipmentName: IPR - PMVV16143
          EquipmentSpeed: 48
          unSafeAct: Driver Fatigue
          unSafeActUtcDate: '2022-01-01 14:45:04'
          ReportTime: '2022-01-01 15:14:51'
          Shift: 2
          Duration: 7
          Direction: East
          Angle: 110
          SiteName: IPR - HAULING COAL
          ValidationStatus: Validated
          FollowupStatus: Close
          DeviationEvidences:
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDdfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDhfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDFfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
        - Longitude: '116.278100'
          Latitude: '0.472105'
          TicketNumber: IPR - PMVV16117-PDSM00000309
          DeviationId: 286926
          OperatorId: null
          OperatorName: ''
          EquipmentId: 009902517A
          EquipmentName: IPR - PMVV16117
          EquipmentSpeed: 52
          unSafeAct: Driver Fatigue
          unSafeActUtcDate: '2022-01-01 12:39:24'
          ReportTime: '2022-01-01 13:10:46'
          Shift: 2
          Duration: 7
          Direction: East
          Angle: 102
          SiteName: IPR - HAULING COAL
          ValidationStatus: Validated
          FollowupStatus: Close
          DeviationEvidences:
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzQxL0NIQU5ORUxfMDdfMjAyMjAxMDEyMDM5MjFfMjAyMjAxMDEyMDM5MjcubXA0
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzQxL0NIQU5ORUxfMDhfMjAyMjAxMDEyMDM5MjFfMjAyMjAxMDEyMDM5MjcubXA0
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzQxL0NIQU5ORUxfMDFfMjAyMjAxMDEyMDM5MjFfMjAyMjAxMDEyMDM5MjcubXA0
        - Longitude: '116.275741'
          Latitude: '0.472320'
          TicketNumber: IPR - PMVV16117-PDSM00000324
          DeviationId: 286941
          OperatorId: null
          OperatorName: ''
          EquipmentId: 009902517A
          EquipmentName: IPR - PMVV16117
          EquipmentSpeed: 43
          unSafeAct: Driver Fatigue
          unSafeActUtcDate: '2022-01-01 12:39:05'
          ReportTime: '2022-01-01 13:26:35'
          Shift: 2
          Duration: 7
          Direction: East
          Angle: 90
          SiteName: IPR - HAULING COAL
          ValidationStatus: Validated
          FollowupStatus: Close
          DeviationEvidences:
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzU4L0NIQU5ORUxfMDdfMjAyMjAxMDEyMDM5MDJfMjAyMjAxMDEyMDM5MDgubXA0
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzU4L0NIQU5ORUxfMDhfMjAyMjAxMDEyMDM5MDJfMjAyMjAxMDEyMDM5MDgubXA0
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2NzU4L0NIQU5ORUxfMDFfMjAyMjAxMDEyMDM5MDJfMjAyMjAxMDEyMDM5MDgubXA0
        - Longitude: '116.275331'
          Latitude: '0.472320'
          TicketNumber: IPR - PMVV16117-PDSM00000371
          DeviationId: 286988
          OperatorId: null
          OperatorName: ''
          EquipmentId: 009902517A
          EquipmentName: IPR - PMVV16117
          EquipmentSpeed: 39
          unSafeAct: Driver Fatigue
          unSafeActUtcDate: '2022-01-01 12:39:01'
          ReportTime: '2022-01-01 14:10:09'
          Shift: 2
          Duration: 7
          Direction: East
          Angle: 90
          SiteName: IPR - HAULING COAL
          ValidationStatus: Validated
          FollowupStatus: Close
          DeviationEvidences:
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2Nzk1L0NIQU5ORUxfMDdfMjAyMjAxMDEyMDM4NThfMjAyMjAxMDEyMDM5MDQubXA0
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2Nzk1L0NIQU5ORUxfMDhfMjAyMjAxMDEyMDM4NThfMjAyMjAxMDEyMDM5MDQubXA0
            - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2Nzk1L0NIQU5ORUxfMDFfMjAyMjAxMDEyMDM4NThfMjAyMjAxMDEyMDM5MDQubXA0
      total_data: 4
    type: object
    properties:
      success:
        type: boolean
      error:
        type: string
      message:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/Datum3'
      total_data:
        type: integer
        format: int32
    required:
      - success
      - error
      - message
      - data
      - total_data
  Datum3:
    title: Datum3
    example:
      Longitude: '116.569951'
      Latitude: '0.292716'
      TicketNumber: IPR - PMVV16143-PDSM00000425
      DeviationId: 287042
      OperatorId: null
      OperatorName: ''
      EquipmentId: 00990268AE
      EquipmentName: IPR - PMVV16143
      EquipmentSpeed: 48
      unSafeAct: Driver Fatigue
      unSafeActUtcDate: '2022-01-01 14:45:04'
      ReportTime: '2022-01-01 15:14:51'
      Shift: 2
      Duration: 7
      Direction: East
      Angle: 110
      SiteName: IPR - HAULING COAL
      ValidationStatus: Validated
      FollowupStatus: Close
      DeviationEvidences:
        - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDdfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
        - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDhfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
        - path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDFfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
    type: object
    properties:
      Longitude:
        type: string
      Latitude:
        type: string
      TicketNumber:
        type: string
      DeviationId:
        type: integer
        format: int32
      OperatorId:
        type: string
      OperatorName:
        type: string
      EquipmentId:
        type: string
      EquipmentName:
        type: string
      EquipmentSpeed:
        type: integer
        format: int32
      unSafeAct:
        type: string
      unSafeActUtcDate:
        type: string
      ReportTime:
        type: string
      Shift:
        type: integer
        format: int32
      Duration:
        type: integer
        format: int32
      Direction:
        type: string
      Angle:
        type: integer
        format: int32
      SiteName:
        type: string
      ValidationStatus:
        type: string
      FollowupStatus:
        type: string
      DeviationEvidences:
        type: array
        items:
          $ref: '#/definitions/DeviationEvidence'
    required:
      - Longitude
      - Latitude
      - TicketNumber
      - DeviationId
      - OperatorId
      - OperatorName
      - EquipmentId
      - EquipmentName
      - EquipmentSpeed
      - unSafeAct
      - unSafeActUtcDate
      - ReportTime
      - Shift
      - Duration
      - Direction
      - Angle
      - SiteName
      - ValidationStatus
      - FollowupStatus
      - DeviationEvidences
  DeviationEvidence:
    title: DeviationEvidence
    example:
      path: http://147.139.186.204:12057/api/v1/basic/mediafile/view?key=zT908g2j9nhExsAmW2pQav62OZEv5FmQhFUqTjrDPjg%3D&dir=RDovRXZpZGVuY2VEYXRhLzIwMjItMDEtMDEvNDA2ODkxL0NIQU5ORUxfMDdfMjAyMjAxMDEyMjQ1MDFfMjAyMjAxMDEyMjQ1MDcubXA0
    type: object
    properties:
      path:
        type: string
    required:
      - path
tags:
  - name: V2
